runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: airup_api.APPLICATION

- url: /.*
  script: worker.app

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: "1.0"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
